services:
  # app:
  #   build: .
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - DATABASE_URL="postgresql://postgres:asdf1234@localhost:5432/ecommnerce_recommendation?schema=public"
  #     - REDIS_PASSWORD=password
  #   depends_on:
  #     - redis

  redis:
    image: redis:6.2-alpine
    command: redis-server --requirepass password
    ports:
      - "6379:6379"

  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app